use database timeout property for post-start
[#158563763]

diff --git a/jobs/policy-server/templates/post-start.erb b/jobs/policy-server/templates/post-start.erb
--- a/jobs/policy-server/templates/post-start.erb
+++ b/jobs/policy-server/templates/post-start.erb
@@ -4,7 +4,14 @@
 source /var/vcap/packages/networking-ctl-utils/ctl_util.sh
 
 export URL="127.0.0.1:<%= p("listen_port") %>"
-export TIMEOUT=25
+export TIMEOUT=<%= p("database.connect_timeout_seconds") %>
 
-exit $(wait_for_server_to_become_healthy "${URL}" "${TIMEOUT}")
+exit_code=$(wait_for_server_to_become_healthy "${URL}" "${TIMEOUT}")
+
+if [ ! ${exit_code} -eq 0 ]
+then
+    echo "policy server failed to start within ${TIMEOUT} seconds"
+fi
+
+exit ${exit_code}
 <% end %>
