Stop migrating policy db when constructing stores, take 2
previous commit(s) move migrations to pre-start

[#158395941]

diff --git a/jobs/policy-server/templates/pre-start.erb b/jobs/policy-server/templates/pre-start.erb
--- a/jobs/policy-server/templates/pre-start.erb
+++ b/jobs/policy-server/templates/pre-start.erb
@@ -5,7 +5,14 @@
 # ensure bosh-dns is up and running
 /var/vcap/jobs/bosh-dns/bin/wait
 
-/var/vcap/packages/policy-server/bin/migrate-db \
-  -config-file=/var/vcap/jobs/policy-server/config/policy-server.json
+exit_code=$(/var/vcap/packages/policy-server/bin/migrate-db \
+  -config-file=/var/vcap/jobs/policy-server/config/policy-server.json)
+
+if [ ! ${exit_code} -eq 0 ]
+then
+    echo "policy server failed to start within ${TIMEOUT} seconds"
+fi
+
+exit ${exit_code}
 
 <% end %>
