Improve stop behavior in ctl scripts
- Only send signals once
- Wait for process to exit before escalating to next signal

[#140428183]

Signed-off-by: Gabe Rosenhouse <grosenhouse@pivotal.io>

diff --git a/jobs/cni-flannel/templates/flanneld_ctl.erb b/jobs/cni-flannel/templates/flanneld_ctl.erb
--- a/jobs/cni-flannel/templates/flanneld_ctl.erb
+++ b/jobs/cni-flannel/templates/flanneld_ctl.erb
@@ -38,6 +38,53 @@ mkdir -p /var/vcap/sys/log/monit
 exec 1>> /var/vcap/sys/log/monit/flanneld.out.log
 exec 2>> /var/vcap/sys/log/monit/flanneld.err.log
 
+function wait_pid() {
+  pid=$1
+  shift
+  max_checks=$1
+  shift
+
+  checks=$max_checks
+  while [ -e "/proc/$pid" ]; do
+    checks=$((checks - 1))
+    if [ $checks -le 0 ]; then
+      return 1
+    fi
+    sleep 0.1
+  done
+
+  return 0
+}
+
+function stop_process() {
+  local pid
+  pid=$(cat "$PIDFILE")
+
+  echo "stopping..."
+  kill -TERM "$pid"
+  if wait_pid "$pid" 100 ; then
+    rm "$PIDFILE"
+    return 0
+  fi
+
+  echo "unable to stop process using SIGTERM after 10 seconds, will now attempt to SIGQUIT"
+  kill -QUIT "$pid" || true
+  if wait_pid "$pid" 50 ; then
+    rm "$PIDFILE"
+    return 0
+  fi
+
+  echo "unable to stop process using SIGQUIT after 5 seconds, will now attempt to SIGKILL"
+  kill -KILL "$pid" || true
+  if wait_pid "$pid" 50 ; then
+    rm "$PIDFILE"
+    return 0
+  fi
+
+  echo "unable to stop process using SIGKILL after 5 seconds"
+  return 1
+}
+
 case $1 in
 
   start)
@@ -70,10 +117,7 @@ case $1 in
     ;;
 
   stop)
-    if [ -f $PIDFILE ]; then
-      kill -9 `cat $PIDFILE` || true
-      rm -f $PIDFILE
-    fi
+    stop_process
     ;;
 
   *)
diff --git a/jobs/policy-server/templates/policy-server_ctl.erb b/jobs/policy-server/templates/policy-server_ctl.erb
--- a/jobs/policy-server/templates/policy-server_ctl.erb
+++ b/jobs/policy-server/templates/policy-server_ctl.erb
@@ -11,6 +11,52 @@ mkdir -p /var/vcap/sys/log/monit
 exec 1>> /var/vcap/sys/log/monit/policy-server.out.log
 exec 2>> /var/vcap/sys/log/monit/policy-server.err.log
 
+function wait_pid() {
+  pid=$1
+  shift
+  max_checks=$1
+  shift
+
+  checks=$max_checks
+  while [ -e "/proc/$pid" ]; do
+    checks=$((checks - 1))
+    if [ $checks -le 0 ]; then
+      return 1
+    fi
+    sleep 0.1
+  done
+
+  return 0
+}
+
+function stop_process() {
+  local pid
+  pid=$(cat "$PIDFILE")
+
+  echo "stopping..."
+  kill -TERM "$pid"
+  if wait_pid "$pid" 100 ; then
+    rm "$PIDFILE"
+    return 0
+  fi
+
+  echo "unable to stop process using SIGTERM after 10 seconds, will now attempt to SIGQUIT"
+  kill -QUIT "$pid" || true
+  if wait_pid "$pid" 50 ; then
+    rm "$PIDFILE"
+    return 0
+  fi
+
+  echo "unable to stop process using SIGQUIT after 5 seconds, will now attempt to SIGKILL"
+  kill -KILL "$pid" || true
+  if wait_pid "$pid" 50 ; then
+    rm "$PIDFILE"
+    return 0
+  fi
+
+  echo "unable to stop process using SIGKILL after 5 seconds"
+  return 1
+}
 
 case $1 in
 
@@ -30,7 +76,7 @@ case $1 in
 
   stop)
 
-    kill -INT $(cat $PIDFILE)
+    stop_process
 
     ;;
 
diff --git a/jobs/vxlan-policy-agent/templates/vxlan-policy-agent_ctl.erb b/jobs/vxlan-policy-agent/templates/vxlan-policy-agent_ctl.erb
--- a/jobs/vxlan-policy-agent/templates/vxlan-policy-agent_ctl.erb
+++ b/jobs/vxlan-policy-agent/templates/vxlan-policy-agent_ctl.erb
@@ -10,6 +10,52 @@ mkdir -p /var/vcap/sys/log/monit
 exec 1>> /var/vcap/sys/log/monit/vxlan-policy-agent.out.log
 exec 2>> /var/vcap/sys/log/monit/vxlan-policy-agent.err.log
 
+function wait_pid() {
+  pid=$1
+  shift
+  max_checks=$1
+  shift
+
+  checks=$max_checks
+  while [ -e "/proc/$pid" ]; do
+    checks=$((checks - 1))
+    if [ $checks -le 0 ]; then
+      return 1
+    fi
+    sleep 0.1
+  done
+
+  return 0
+}
+
+function stop_process() {
+  local pid
+  pid=$(cat "$PIDFILE")
+
+  echo "stopping..."
+  kill -TERM "$pid"
+  if wait_pid "$pid" 100 ; then
+    rm "$PIDFILE"
+    return 0
+  fi
+
+  echo "unable to stop process using SIGTERM after 10 seconds, will now attempt to SIGQUIT"
+  kill -QUIT "$pid" || true
+  if wait_pid "$pid" 50 ; then
+    rm "$PIDFILE"
+    return 0
+  fi
+
+  echo "unable to stop process using SIGQUIT after 5 seconds, will now attempt to SIGKILL"
+  kill -KILL "$pid" || true
+  if wait_pid "$pid" 50 ; then
+    rm "$PIDFILE"
+    return 0
+  fi
+
+  echo "unable to stop process using SIGKILL after 5 seconds"
+  return 1
+}
 
 case $1 in
 
@@ -32,29 +78,7 @@ case $1 in
 
   stop)
 
-    pid=$(cat $PIDFILE)
-
-    for i in $(seq 15); do
-      echo "sending INT to ${pid}..."
-      if kill -INT $pid; then
-        sleep 1
-      else
-        echo "exited"
-        exit 0
-      fi
-    done
-
-    echo "timed out; sending SIGQUIT followed by SIGKILL to ${pid}..."
-    if kill -QUIT $pid; then
-      sleep 5
-
-      echo "killing ${pid}..."
-      kill -9 $pid || true
-      rm  -f $PIDFILE
-    fi
-
-    echo "killed"
-
+    stop_process
     ;;
 
   *)
